project_id = "onlhhefpjkcjkscsnoqk"

[auth]
# Enable phone auth
enable_signup = true

[auth.sms]
# Enable OTP via SMS
enable_signup = true
enable_confirmations = false

[functions.wallet]
verify_jwt = false

[functions.transfers]
verify_jwt = false

[functions.requests]
verify_jwt = false

[functions.transactions]
verify_jwt = false

[functions.cards]
verify_jwt = false

[functions.banking]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.auth-otp]
verify_jwt = false